# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wang_similarity <- function(otr, nodes, contribution, correct = FALSE) {
    .Call(`_simAnn_wang_similarity`, otr, nodes, contribution, correct)
}

wang_similarity_sv <- function(sv) {
    .Call(`_simAnn_wang_similarity_sv`, sv)
}

clusterSimilarTermsCPP <- function(sim_matrix, terms_vec, parentMap, termNames, icScores, annotationsList, annotationsNames, threshold = 0.8) {
    .Call(`_simAnn_clusterSimilarTermsCPP`, sim_matrix, terms_vec, parentMap, termNames, icScores, annotationsList, annotationsNames, threshold)
}

splitString <- function(s, delim) {
    .Call(`_simAnn_splitString`, s, delim)
}

unionChar <- function(v1, v2) {
    .Call(`_simAnn_unionChar`, v1, v2)
}

updateAnnotations <- function(tree, new_annot, use_background = FALSE) {
    .Call(`_simAnn_updateAnnotations`, tree, new_annot, use_background)
}

calculateNodeDepths <- function(tree) {
    .Call(`_simAnn_calculateNodeDepths`, tree)
}

calculateUniversalIC <- function(tree, verbose = TRUE) {
    .Call(`_simAnn_calculateUniversalIC`, tree, verbose)
}

getTermAnnotations <- function(otr, nodes) {
    .Call(`_simAnn_getTermAnnotations`, otr, nodes)
}

cross_min <- function(x) {
    .Call(`_simAnn_cross_min`, x)
}

cross_max <- function(x) {
    .Call(`_simAnn_cross_max`, x)
}

countOffspring <- function(tree, includeSelf = FALSE) {
    .Call(`_simAnn_countOffspring`, tree, includeSelf)
}

calculateOffspringIC <- function(tree, verbose = TRUE) {
    .Call(`_simAnn_calculateOffspringIC`, tree, verbose)
}

calculateIC <- function(tree, method = "universal", useCache = TRUE, verbose = TRUE) {
    .Call(`_simAnn_calculateIC`, tree, method, useCache, verbose)
}

calculateUniversal <- function(tree, useCache = TRUE, verbose = TRUE) {
    .Call(`_simAnn_calculateUniversal`, tree, useCache, verbose)
}

calculateOffspring <- function(tree, useCache = TRUE, verbose = TRUE) {
    .Call(`_simAnn_calculateOffspring`, tree, useCache, verbose)
}

countAnnotations <- function(tree, unify = TRUE) {
    .Call(`_simAnn_countAnnotations`, tree, unify)
}

getLongestDistToOffspring <- function(tree, fromNodes, backgroundNodes = logical(0)) {
    .Call(`_simAnn_getLongestDistToOffspring`, tree, fromNodes, backgroundNodes)
}

getShortestDistToOffspring <- function(tree, fromNodes, backgroundNodes = logical(0)) {
    .Call(`_simAnn_getShortestDistToOffspring`, tree, fromNodes, backgroundNodes)
}

getGroupAncestors <- function(tree, nodes, type = 1L, includeSelf = FALSE) {
    .Call(`_simAnn_getGroupAncestors`, tree, nodes, type, includeSelf)
}

findMaxAncestorID <- function(tree, nodes, values, useLongestPath = TRUE) {
    .Call(`_simAnn_findMaxAncestorID`, tree, nodes, values, useLongestPath)
}

findMaxAncestorValues <- function(tree, nodes, values) {
    .Call(`_simAnn_findMaxAncestorValues`, tree, nodes, values)
}

calculateAncestorSimilarity <- function(tree, termIds) {
    .Call(`_simAnn_calculateAncestorSimilarity`, tree, termIds)
}

calculateWangIC <- function(tree, contribution) {
    .Call(`_simAnn_calculateWangIC`, tree, contribution)
}

